apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  namespace: midterm2
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      namespace: midterm2
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-pay:0.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: MYSQL
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  namespace: midterm2
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: idk